#!/usr/bin/env bash
# Generate an experience document from the current session
# Usage: ./generate-experience.sh <session-title-or-topic>
set -euo pipefail

KB_DIR="$HOME/.hermes-kb"
DATE_TAG=$(date '+%Y-%m-%d')
TOPIC="${1:-unknown-task}"
# Sanitize topic for filename
SAFE_TOPIC=$(echo "$TOPIC" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//')
FILENAME="experience/${DATE_TAG}-${SAFE_TOPIC}.md"
FILEPATH="$KB_DIR/$FILENAME"

cat > "$FILEPATH" << EXPEOF
# Experience Log: ${DATE_TAG}

## Topic
${TOPIC}

## Summary

<!-- What was this session about? -->

## Key Learnings

1. 
2. 
3. 

## Skills Used / Created

- 

## Decisions Made

- 

## Pitfalls Encountered

- 

## Next Steps / TODO

- 

---
*Auto-generated by Hermes Agent | gilliansoso/hermes-knowledge-base*
EXPEOF

echo "✓ Experience document created: $FILENAME"
echo "  → $FILEPATH"
